package br.com.tempodecrescer;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.provider.Settings;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

public class MainActivity extends Activity {
    Store s;LinearLayout page,body,nav;int tab=0;boolean unlocked=false;long unlockedAt;Handler handler=new Handler();boolean loading;
    int ink=Color.rgb(244,249,255),green=Color.rgb(185,243,107),muted=Color.rgb(142,169,189);
    @Override public void onCreate(Bundle b){super.onCreate(b);s=new Store(this);if(getIntent().getBooleanExtra("tasks",false))tab=1;render();if(s.paired()&&!getIntent().getBooleanExtra("native",false)&&b==null)startActivity(new Intent(this,PanelActivity.class));}
    @Override protected void onResume(){super.onResume();if(s!=null){if(System.currentTimeMillis()-unlockedAt>300000)unlocked=false;render();}}
    @Override protected void onStop(){unlocked=false;super.onStop();}
    int dp(int n){return (int)(n*getResources().getDisplayMetrics().density);}
    LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    TextView text(LinearLayout dest,String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(7));dest.addView(t);return t;}
    void heading(LinearLayout d,String v,int size){text(d,v,size,ink).setTypeface(null,Typeface.BOLD);}
    LinearLayout card(){LinearLayout c=column();c.setPadding(dp(20),dp(16),dp(20),dp(16));GradientDrawable background=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(16,34,49),Color.rgb(9,23,34)});background.setCornerRadius(dp(22));background.setStroke(dp(1),Color.rgb(28,58,80));c.setBackground(background);c.setElevation(dp(12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(2),dp(12),dp(2),dp(14));body.addView(c,p);return c;}
    Button button(LinearLayout d,String label,Runnable action){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(Color.rgb(16,32,10));GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(211,255,155),Color.rgb(168,223,96)});g.setCornerRadius(dp(14));b.setBackground(g);b.setElevation(dp(7));b.setPadding(dp(12),dp(8),dp(12),dp(8));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,dp(12),0,dp(8));d.addView(b,p);b.setOnClickListener(v->action.run());return b;}
    EditText input(LinearLayout d,String label,String value,boolean number){text(d,label,14,muted);EditText e=new EditText(this);e.setSingleLine();e.setText(value);e.setTextColor(ink);e.setInputType(number?InputType.TYPE_CLASS_NUMBER:InputType.TYPE_CLASS_TEXT);d.addView(e,new LinearLayout.LayoutParams(-1,dp(52)));return e;}
    void toast(String v){Toast.makeText(this,v,Toast.LENGTH_LONG).show();}
    void render(){if(isFinishing())return;
        page=column();page.setBackgroundColor(Color.rgb(6,16,25));page.setPadding(dp(18),dp(12),dp(18),dp(10));
        page.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(dp(18),insets.getSystemWindowInsetTop()+dp(12),dp(18),insets.getSystemWindowInsetBottom()+dp(10));return insets;});setContentView(page);page.requestApplyInsets();
        LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);ImageView crest=new ImageView(this);crest.setImageResource(br.com.tempodecrescer.R.drawable.crest_icon);brand.addView(crest,new LinearLayout.LayoutParams(dp(52),dp(56)));LinearLayout brandText=column();brandText.setPadding(dp(12),0,0,0);heading(brandText,"Borges Franco",19);text(brandText,"TEMPO DE CRESCER",11,green);brand.addView(brandText);page.addView(brand);
        heading(page,tab==0?"Tempo para tudo.":tab==1?"Conquistas do dia":"Cuidar e acompanhar",26);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=column();scroll.addView(body);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        if(!s.prefs.contains("roleChosen")){welcome();return;}
        if(tab==0)today();else if(tab==1)tasks();else settings();
        nav=new LinearLayout(this);String[] names={"Hoje","Tarefas","Responsável"};for(int i=0;i<3;i++){final int n=i;Button b=new Button(this);b.setText(names[i]);b.setAllCaps(false);b.setTextSize(12);b.setTextColor(tab==i?green:muted);nav.addView(b,new LinearLayout.LayoutParams(0,dp(54),1));b.setOnClickListener(v->{tab=n;render();});}page.addView(nav);
    }
    void welcome(){LinearLayout c=card();heading(c,"Mais equilíbrio, juntos.",25);text(c,"Escolha onde este aplicativo está sendo instalado. No aparelho da criança, configure os aplicativos e as permissões. No seu aparelho, acompanhe e aprove os bônus à distância.",17,muted);
        button(c,"Este é o celular da criança",()->chooseRole("child"));button(c,"Este é o celular do responsável",()->chooseRole("parent"));}
    void chooseRole(String role){s.prefs.edit().putString("role",role).putBoolean("roleChosen",true).apply();tab=2;render();}
    String duration(long ms){long min=Math.max(0,ms/60000);return min>=60?(min/60)+"h "+(min%60)+"min":min+" min";}
    void today(){if(s.paired())button(body,"Abrir painel atualizado",()->startActivity(new Intent(this,PanelActivity.class)));if(s.parent())familyHeader();JSONObject state=s.state(),config=s.config();long used=s.parent()?(Store.day().equals(state.optString("day"))?state.optLong("used"):0):s.used(s.usage())+s.otherUsed();int total=config.optInt("limit",120)+s.bonus();
        LinearLayout c=card();text(c,s.parent()?"APARELHO DA CRIANÇA":"SEU TEMPO DE HOJE",12,green);heading(c,duration(Math.max(0,total*60000L-used)),42);text(c,"restantes nos aplicativos selecionados",16,muted);
        ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(Math.max(1,total));p.setProgress((int)Math.min(total,used/60000));c.addView(p,new LinearLayout.LayoutParams(-1,dp(12)));
        text(c,"Usado: "+duration(used)+"  •  Limite: "+total+" min",15,ink);if(s.bonus()>0)text(c,"★ +"+s.bonus()+" min conquistados hoje",17,green);
        if(!config.optBoolean("enabled",true))text(c,"Controle pausado pelo responsável",16,muted);
        if(s.parent()&&!s.paired()){text(c,"Conecte este aparelho ao celular da criança para receber os dados.",16,muted);button(c,"Conectar aparelhos",()->{tab=2;render();});}
        else if(!s.parent()&&(!s.usageAllowed()||!s.guardEnabled())){LinearLayout warn=card();heading(warn,"Configuração incompleta",18);text(warn,"O controle precisa das permissões de uso e acessibilidade.",15,muted);button(warn,"Concluir configuração",()->{tab=2;render();});}
        LinearLayout sync=card();heading(sync,"Conexão",18);text(sync,s.paired()?"Vinculado • "+(s.parent()?"responsável":"criança"):"Modo local • neste aparelho",15,muted);
        long last=s.prefs.getLong("lastSync",0);if(last>0)text(sync,"Última atualização: "+new java.text.SimpleDateFormat("dd/MM HH:mm",Locale.getDefault()).format(new Date(last)),14,muted);
        String error=s.prefs.getString("syncError","");if(!error.isEmpty())text(sync,"Sem atualização: "+error+". As regras já recebidas continuam no aparelho da criança.",14,muted);
        if(s.paired())button(sync,loading?"Atualizando…":"Atualizar agora",this::sync);
        if(s.parent()&&s.paired())text(sync,"Uso: "+(state.optBoolean("usageAllowed")?"permitido":"não confirmado")+" • Bloqueio: "+(state.optBoolean("guardEnabled")?"ativo":"não confirmado"),14,muted);
        if(!s.parent()){Map<String,Long> usage=s.usage();LinearLayout apps=card();heading(apps,"Aplicativos controlados",18);JSONArray selected=config.optJSONArray("apps");if(selected==null||selected.length()==0)text(apps,"Nenhum aplicativo selecionado ainda.",15,muted);else for(int i=0;i<selected.length();i++){String pkg=selected.optString(i);text(apps,label(pkg)+" — "+duration(usage.getOrDefault(pkg,0L)),16,ink);}}
    }
    String label(String pkg){try{return getPackageManager().getApplicationLabel(getPackageManager().getApplicationInfo(pkg,0)).toString();}catch(Exception e){return pkg;}}
    void sync(){if(loading)return;loading=true;Remote.sync(this,error->runOnUiThread(()->{loading=false;if(error!=null)toast(error);render();}));}
    void gate(Runnable action){if(unlocked&&System.currentTimeMillis()-unlockedAt<300000){action.run();return;}
        if(System.currentTimeMillis()<s.prefs.getLong("pinWait",0)){toast("Aguarde um minuto antes de tentar novamente.");return;}
        LinearLayout box=column();box.setPadding(dp(24),dp(8),dp(24),0);boolean create=!s.hasPin();EditText pin=input(box,create?"Crie um PIN de 4 a 8 números":"PIN do responsável","",true);pin.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);EditText confirm=create?input(box,"Repita o PIN","",true):null;if(confirm!=null)confirm.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);
        AlertDialog d=new AlertDialog.Builder(this).setTitle(create?"Proteja os ajustes":"Área do responsável").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Continuar",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{String value=pin.getText().toString();try{if(create){if(!value.matches("[0-9]{4,8}")||!value.equals(confirm.getText().toString())){toast("Digite o mesmo PIN de 4 a 8 números nos dois campos.");return;}s.setPin(value);}else if(!s.checkPin(value)){int fails=s.prefs.getInt("pinFails",0)+1;s.prefs.edit().putInt("pinFails",fails%5).putLong("pinWait",fails>=5?System.currentTimeMillis()+60000:0).apply();toast("PIN incorreto.");d.dismiss();return;}
        s.prefs.edit().putInt("pinFails",0).putLong("pinWait",0).apply();unlocked=true;unlockedAt=System.currentTimeMillis();d.dismiss();action.run();}catch(Exception e){toast("Não foi possível salvar o PIN.");}}));d.show();}
    void tasks(){if(s.parent())familyHeader();LinearLayout intro=card();heading(intro,"Pequenos passos, mais tempo",20);text(intro,"Conclua uma tarefa e peça a aprovação do responsável. Cada tarefa pode render um bônus por dia. Os bônus expiram à meia-noite e não liberam o horário de descanso.",15,muted);
        JSONArray tasks=s.config().optJSONArray("tasks");JSONObject state=s.state();JSONObject claims=Store.day().equals(state.optString("day"))?state.optJSONObject("claims"):null;
        if(tasks==null||tasks.length()==0)text(intro,"O responsável ainda não cadastrou tarefas.",16,green);
        for(int i=0;tasks!=null&&i<tasks.length();i++){JSONObject t=tasks.optJSONObject(i);if(t==null)continue;String id=t.optString("id"),status=claims==null?"":claims.optString(id);LinearLayout c=card();heading(c,t.optString("title"),20);text(c,"+"+t.optInt("minutes")+" minutos",22,green);text(c,status.equals("approved")?"✓ Bônus liberado hoje":status.equals("pending")?"Aguardando aprovação":status.equals("rejected")?"Refaça a tarefa e solicite novamente":"Disponível hoje",14,muted);
            if(!s.parent()&&!status.equals("approved")&&!status.equals("pending"))button(c,"Concluí • pedir bônus",()->taskAction(id,"claim"));
            if(status.equals("pending")){button(c,"Responsável: aprovar bônus",()->gate(()->taskAction(id,"approve")));button(c,"Pedir para refazer",()->gate(()->taskAction(id,"reject")));}
        }
        button(intro,"Configurar tarefas e bônus",()->gate(this::taskEditor));
    }
    void taskAction(String id,String action){
        if(s.paired()){request("/api/"+(action.equals("claim")?"child/":"parent/")+action,json("taskId",id),r->{s.state(r.optJSONObject("state"));render();});}else try{s.localTask(id,action);render();}catch(Exception e){toast("Não foi possível atualizar a tarefa.");}}
    JSONObject json(String key,Object value){JSONObject j=new JSONObject();try{j.put(key,value);}catch(Exception ignored){}return j;}
    interface Result {void accept(JSONObject j);}
    void request(String path,JSONObject data,Result action){if(loading){toast("Aguarde a operação atual.");return;}loading=true;Remote.IO.execute(()->{try{JSONObject r=Remote.call(s,path,data);runOnUiThread(()->{loading=false;action.accept(r);});}catch(Exception e){runOnUiThread(()->{loading=false;toast(e.getMessage());});}});}
    boolean editable(){return true;}
    void saveConfig(JSONObject config){if(!editable())return;if(s.paired())request("/api/parent/config",json("config",config),r->{s.config(r.optJSONObject("config"));s.state(r.optJSONObject("state"));toast("Configuração salva. Aguarde a sincronização da criança.");render();});else{s.config(config);toast("Configuração salva.");render();}}
    void taskEditor(){if(!editable())return;LinearLayout box=column();box.setPadding(dp(20),0,dp(20),0);JSONArray arr=s.config().optJSONArray("tasks");final JSONArray tasks=arr==null?new JSONArray():arr;
        ScrollView scroll=new ScrollView(this);scroll.addView(box);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Tarefas e bônus").setView(scroll).setNegativeButton("Fechar",null).create();
        for(int i=0;i<tasks.length();i++){final int index=i;JSONObject task=tasks.optJSONObject(i);button(box,task.optString("title")+" • "+task.optInt("minutes")+" min",()->{dialog.dismiss();editTask(tasks,index);});}
        button(box,"+ Criar tarefa",()->{dialog.dismiss();editTask(tasks,-1);});dialog.show();}
    void editTask(JSONArray tasks,int index){JSONObject old=index<0?new JSONObject():tasks.optJSONObject(index);LinearLayout box=column();box.setPadding(dp(22),0,dp(22),0);EditText title=input(box,"Nome da tarefa",old.optString("title"),false),minutes=input(box,"Bônus em minutos (1 a 240)",""+old.optInt("minutes",15),true);
        AlertDialog d=new AlertDialog.Builder(this).setTitle(index<0?"Nova tarefa":"Editar tarefa").setView(box).setNegativeButton("Cancelar",null).setNeutralButton(index<0?"":"Excluir",(v,w)->{if(index>=0){tasks.remove(index);JSONObject c=s.config();try{c.put("tasks",tasks);saveConfig(c);}catch(Exception ignored){}}}).setPositiveButton("Salvar",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{try{int n=Integer.parseInt(minutes.getText().toString());String name=title.getText().toString().trim();if(name.isEmpty()||name.length()>80||n<1||n>240||tasks.length()>=30&&index<0)throw new Exception();JSONObject t=new JSONObject().put("id",old.optString("id",UUID.randomUUID().toString())).put("title",name).put("minutes",n);if(index<0)tasks.put(t);else tasks.put(index,t);JSONObject c=s.config().put("tasks",tasks);d.dismiss();saveConfig(c);}catch(Exception e){toast("Nome até 80 caracteres, bônus de 1 a 240 minutos e até 30 tarefas.");}}));d.show();}
    void settings(){LinearLayout c=card();heading(c,s.parent()?"Modo responsável":"Modo criança",20);text(c,"Limites, tarefas e conexão ficam protegidos pelo PIN deste aplicativo.",15,muted);
        button(c,unlocked?"Abrir configurações":"Desbloquear configurações",()->gate(()->{renderSettings();}));
        if(unlocked)renderSettings();
        LinearLayout info=card();heading(info,"Como funciona",18);text(info,"O controle se aplica aos aplicativos selecionados. Telefone, tela inicial e configurações do sistema continuam disponíveis. A proteção depende das permissões do Android e pode ser desativada ou removida pelo usuário do aparelho. Não impede desinstalação.",14,muted);
        text(info,"Sem internet, continuam valendo as últimas regras recebidas. Novas regras e aprovações remotas aguardam conexão. Não coletamos mensagens, fotos ou localização.",14,muted);
    }
    void renderSettings(){body.removeAllViews();LinearLayout c=card();heading(c,"Regras de tempo",21);JSONObject config=s.config();
        button(c,config.optBoolean("blocked")?"Liberar bloqueio manual":"Bloquear agora",()->{boolean blocked=!config.optBoolean("blocked");if(s.paired())request("/api/parent/block",json("blocked",blocked),r->{s.config(r.optJSONObject("config"));render();});else try{config.put("blocked",blocked);if(blocked)config.remove("release");saveConfig(config);}catch(Exception ignored){}});
        button(c,"Liberar uso: total, por tempo ou por aplicativo",this::releaseDialog);
        button(c,"Encerrar liberação e voltar às regras",()->applyRelease(json("mode","none")));
        EditText limit=input(c,"Limite diário em minutos (1 a 1440)",""+config.optInt("limit",120),true);Switch enabled=new Switch(this);enabled.setText("Controle de tempo ativo");enabled.setChecked(config.optBoolean("enabled",true));c.addView(enabled);
        Switch rest=new Switch(this);rest.setText("Ativar horário de descanso");rest.setChecked(config.optBoolean("rest"));c.addView(rest);
        final int[] hours={config.optInt("start",1260),config.optInt("end",420)};
        Button start=button(c,"Descanso começa: "+clock(hours[0]),()->{}),end=button(c,"Descanso termina: "+clock(hours[1]),()->{});
        start.setOnClickListener(v->new TimePickerDialog(this,(p,h,m)->{hours[0]=h*60+m;start.setText("Descanso começa: "+clock(hours[0]));},hours[0]/60,hours[0]%60,true).show());
        end.setOnClickListener(v->new TimePickerDialog(this,(p,h,m)->{hours[1]=h*60+m;end.setText("Descanso termina: "+clock(hours[1]));},hours[1]/60,hours[1]%60,true).show());
        button(c,"Salvar regras",()->{try{int n=Integer.parseInt(limit.getText().toString());if(n<1||n>1440)throw new Exception();if(rest.isChecked()&&hours[0]==hours[1]){toast("O início e o fim do descanso devem ser diferentes.");return;}config.put("limit",n).put("enabled",enabled.isChecked()).put("rest",rest.isChecked()).put("start",hours[0]).put("end",hours[1]);saveConfig(config);}catch(Exception e){toast("Informe de 1 a 1440 minutos.");}});
        if(!s.parent())button(c,"Escolher aplicativos controlados",this::appPicker);else {text(c,"Criança selecionada: "+s.prefs.getString("childName","Nenhuma"),16,green);text(c,"Escolha os aplicativos no aparelho da criança com o PIN. Para outra criança, use o menu Hoje.",14,muted);}
        button(c,"Configurar tarefas e bônus",this::taskEditor);
        if(!s.parent()){LinearLayout perms=card();heading(perms,"Permissões do aparelho",20);button(perms,(s.usageAllowed()?"✓ ":"1. ")+"Acesso ao uso",()->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS)));button(perms,(s.guardEnabled()?"✓ ":"2. ")+"Ativar bloqueio",()->new AlertDialog.Builder(this).setTitle("Permitir controle parental").setMessage("A acessibilidade identifica o aplicativo aberto para exibir a pausa. Não lê o conteúdo da tela. Para conectar os aparelhos, enviamos ao servidor o tempo total dos apps selecionados, tarefas e estado das permissões. Você pode desativar o serviço nas configurações do Android.").setNegativeButton("Cancelar",null).setPositiveButton("Entendi • abrir ajustes",(a,b)->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))).show());text(perms,"Em alguns Androids, abra Informações do app → menu ⋮ → Permitir configurações restritas antes de ativar a acessibilidade. Na bateria, permita atividade em segundo plano para evitar interrupções.",14,muted);}
        connection();button(body,"Encerrar acesso do responsável",()->{unlocked=false;render();});
    }
    String clock(int n){return String.format(Locale.US,"%02d:%02d",n/60,n%60);}
    void releaseDialog(){new AlertDialog.Builder(this).setTitle("Como deseja liberar?").setItems(new String[]{"Total: até o responsável encerrar","Todos os aplicativos por um período","Escolher um ou vários aplicativos"},(dialog,which)->{if(which==0){new AlertDialog.Builder(this).setTitle("Liberar totalmente?").setMessage("Os aplicativos controlados ficarão livres, inclusive durante o descanso, até você encerrar a liberação.").setNegativeButton("Cancelar",null).setPositiveButton("Liberar",(a,b)->{try{applyRelease(new JSONObject().put("mode","all").put("minutes",0));}catch(Exception ignored){}}).show();return;}
        LinearLayout box=column();box.setPadding(dp(22),0,dp(22),0);EditText minutes=input(box,"Minutos (0 = até você encerrar)","30",true);text(box,"Esta liberação ignora o limite e o descanso para os aplicativos escolhidos. Depois do prazo, voltam as regras anteriores.",14,muted);JSONArray apps=s.config().optJSONArray("apps");List<CheckBox> checks=new ArrayList<>();List<String> packages=new ArrayList<>();if(which==2)for(int i=0;apps!=null&&i<apps.length();i++){String pkg=apps.optString(i);CheckBox check=new CheckBox(this);check.setText(label(pkg));box.addView(check);checks.add(check);packages.add(pkg);}ScrollView scroll=new ScrollView(this);scroll.addView(box);AlertDialog d=new AlertDialog.Builder(this).setTitle("Liberação especial").setView(scroll).setNegativeButton("Cancelar",null).setPositiveButton("Liberar",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{try{int n=Integer.parseInt(minutes.getText().toString());if(n<0||n>1440)throw new Exception();JSONArray selected=new JSONArray();for(int i=0;i<checks.size();i++)if(checks.get(i).isChecked())selected.put(packages.get(i));if(which==2&&selected.length()==0){toast("Selecione pelo menos um aplicativo.");return;}applyRelease(new JSONObject().put("mode",which==1?"all":"apps").put("minutes",n).put("apps",selected));d.dismiss();}catch(Exception e){toast("Informe de 0 a 1440 minutos.");}}));d.show();}).show();}
    void applyRelease(JSONObject data){if(s.paired())request("/api/parent/release",data,r->{s.config(r.optJSONObject("config"));render();});else try{JSONObject c=s.config();if(data.optString("mode").equals("none"))c.remove("release");else c.put("release",new JSONObject().put("all",data.optString("mode").equals("all")).put("apps",data.optJSONArray("apps")==null?new JSONArray():data.getJSONArray("apps")).put("until",data.optInt("minutes")==0?0:System.currentTimeMillis()+data.optInt("minutes")*60000L));saveConfig(c);}catch(Exception e){toast("Não foi possível liberar.");}}
    void appPicker(){Intent query=new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> raw=getPackageManager().queryIntentActivities(query,0);TreeMap<String,String> apps=new TreeMap<>();Set<String> critical=new HashSet<>(Arrays.asList(getPackageName(),"com.android.settings","com.android.systemui","com.android.phone"));
        android.telecom.TelecomManager tel=(android.telecom.TelecomManager)getSystemService(TELECOM_SERVICE);if(tel!=null&&tel.getDefaultDialerPackage()!=null)critical.add(tel.getDefaultDialerPackage());ResolveInfo home=getPackageManager().resolveActivity(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME),PackageManager.MATCH_DEFAULT_ONLY);if(home!=null)critical.add(home.activityInfo.packageName);
        for(ResolveInfo r:raw){String pkg=r.activityInfo.packageName;if(!critical.contains(pkg))apps.put(r.loadLabel(getPackageManager()).toString()+"\n"+pkg,pkg);}String[] labels=apps.keySet().toArray(new String[0]),packages=apps.values().toArray(new String[0]);boolean[] checked=new boolean[labels.length];for(int i=0;i<checked.length;i++)checked[i]=s.selected(packages[i]);
        new AlertDialog.Builder(this).setTitle("Aplicativos com limite").setMultiChoiceItems(labels,checked,(d,i,b)->checked[i]=b).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",(d,w)->{JSONArray selected=new JSONArray();JSONObject appLabels=new JSONObject();for(int i=0;i<checked.length;i++)if(checked[i]){selected.put(packages[i]);try{appLabels.put(packages[i],label(packages[i]));}catch(Exception ignored){}}JSONObject config=s.config();try{config.put("apps",selected).put("appLabels",appLabels);if(s.paired())request("/api/parent/apps",json("apps",selected).put("appLabels",appLabels),r->{s.config(r.optJSONObject("config"));render();});else saveConfig(config);}catch(Exception ignored){}}).show();
    }
    void connection(){LinearLayout c=card();heading(c,"Conectar à distância",20);if(s.paired()){text(c,"Perfil: "+s.prefs.getString("childName","Criança")+". As regras ficam salvas mesmo sem internet.",15,muted);button(c,"Sincronizar agora",this::sync);if(s.parent()){button(c,"Gerenciar crianças e aparelhos",this::familyList);button(c,"+ Adicionar criança ou aparelho",()->pairDialog(false));}else{String code=s.prefs.getString("pairCode","");if(!code.isEmpty()&&System.currentTimeMillis()<s.prefs.getLong("pairExpires",0))button(c,"Mostrar código de pareamento",()->showCode(code));button(c,"Gerar novo código (se não vinculado)",()->request("/api/code",new JSONObject(),r->{s.prefs.edit().putString("pairCode",r.optString("code")).putLong("pairExpires",System.currentTimeMillis()+600000).apply();showCode(r.optString("code"));}));}return;}
        EditText server=input(c,"Servidor seguro (HTTPS)",s.prefs.getString("server",Remote.DEFAULT_URL),false);
        if(s.parent())button(c,"Entrar em família existente",()->{s.prefs.edit().putString("server",server.getText().toString().trim().replaceAll("/+$","")).apply();joinFamily();});
        if(s.parent()){text(c,"Gere um código em cada aparelho da criança e adicione aqui. Você pode cadastrar as cinco crianças, cada uma com suas regras.",14,muted);button(c,"+ Adicionar criança e aparelho",()->{s.prefs.edit().putString("server",server.getText().toString().trim().replaceAll("/+$","")).apply();pairDialog(false);});}
        else{EditText name=input(c,"Nome da criança",s.prefs.getString("childName",""),false),device=input(c,"Nome deste aparelho","Celular",false);button(c,"Gerar código de pareamento",()->{if(name.getText().toString().trim().isEmpty()){toast("Informe o nome da criança.");return;}s.prefs.edit().putString("server",server.getText().toString().trim().replaceAll("/+$","")).putString("childName",name.getText().toString().trim()).apply();JSONObject data=json("config",s.config());try{data.put("name",name.getText().toString().trim()).put("deviceName",device.getText().toString().trim());}catch(Exception ignored){}request("/api/register",data,r->{s.prefs.edit().putString("token",r.optString("token")).putString("localToken",r.optString("localToken")).putString("pairCode",r.optString("code")).putLong("pairExpires",System.currentTimeMillis()+600000).apply();showCode(r.optString("code"));render();});});}
        String code=s.prefs.getString("pairCode","");if(!code.isEmpty()&&System.currentTimeMillis()<s.prefs.getLong("pairExpires",0))button(c,"Mostrar código",()->showCode(code));
    }
    void showCode(String code){new AlertDialog.Builder(this).setTitle("Código de pareamento").setMessage(code+"\n\nVálido por 10 minutos. Digite somente no aparelho do responsável. Não compartilhe com outras pessoas.").setPositiveButton("Entendi",null).show();}
    void joinFamily(){LinearLayout box=column();box.setPadding(dp(22),0,dp(22),0);EditText code=input(box,"Convite gerado pelo outro responsável","",false);AlertDialog d=new AlertDialog.Builder(this).setTitle("Entrar na mesma família").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Vincular",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->request("/api/pair",json("code",code.getText().toString().trim().toUpperCase(Locale.US)),r->{s.prefs.edit().putString("token",r.optString("token")).apply();d.dismiss();selectChild(r);startActivity(new Intent(this,PanelActivity.class));})));d.show();}
    void familyHeader(){LinearLayout c=card();text(c,"FAMÍLIA • PERFIL ATUAL",12,green);heading(c,s.prefs.getString("childName","Cadastre suas crianças"),22);button(c,"Crianças e aparelhos",()->gate(this::familyList));}
    void selectChild(JSONObject r){s.config(r.optJSONObject("config"));s.state(r.optJSONObject("state"));s.prefs.edit().putString("childId",r.optString("childId",r.optString("id"))).putString("childName",r.optString("name")).putLong("lastSync",System.currentTimeMillis()).apply();render();}
    void familyList(){if(!s.paired()){tab=2;unlocked=true;render();return;}request("/api/parent/list",new JSONObject(),r->{LinearLayout box=column();box.setPadding(dp(20),0,dp(20),dp(20));ScrollView scroll=new ScrollView(this);scroll.addView(box);AlertDialog d=new AlertDialog.Builder(this).setTitle("Crianças e aparelhos").setView(scroll).setNegativeButton("Fechar",null).create();JSONArray children=r.optJSONArray("children");for(int i=0;children!=null&&i<children.length();i++){JSONObject child=children.optJSONObject(i);JSONObject state=child.optJSONObject("state");button(box,child.optString("name")+" • +"+state.optInt("bonus")+" min de bônus",()->{d.dismiss();selectChild(child);});JSONArray devices=state.optJSONArray("devices");for(int j=0;devices!=null&&j<devices.length();j++){JSONObject device=devices.optJSONObject(j);long last=device.optLong("lastSeen");text(box,"   "+device.optString("name")+" • "+(last>0?new java.text.SimpleDateFormat("dd/MM HH:mm",Locale.getDefault()).format(new Date(last)):"aguardando conexão"),13,muted);}}
        button(box,"+ Adicionar outra criança",()->{d.dismiss();pairDialog(false);});if(!s.prefs.getString("childId","").isEmpty())button(box,"+ Outro aparelho para "+s.prefs.getString("childName","esta criança"),()->{d.dismiss();pairDialog(true);});d.show();});}
    void pairDialog(boolean existing){LinearLayout box=column();box.setPadding(dp(22),0,dp(22),0);EditText name=input(box,"Nome da criança",existing?s.prefs.getString("childName",""):"",false);if(existing)name.setEnabled(false);EditText device=input(box,"Nome do aparelho (ex.: tablet)","Celular",false),code=input(box,"Código gerado no aparelho da criança","",false);AlertDialog d=new AlertDialog.Builder(this).setTitle(existing?"Adicionar aparelho":"Adicionar criança").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Vincular",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{if(name.getText().toString().trim().isEmpty()||code.getText().toString().trim().isEmpty()){toast("Preencha o nome e o código.");return;}JSONObject data=json("code",code.getText().toString().trim().toUpperCase(Locale.US));try{data.put("name",name.getText().toString().trim()).put("deviceName",device.getText().toString().trim());if(existing)data.put("childId",s.prefs.getString("childId",""));}catch(Exception ignored){}request("/api/pair",data,r->{if(r.has("token"))s.prefs.edit().putString("token",r.optString("token")).apply();d.dismiss();selectChild(r);toast("Criança e aparelho vinculados.");});}));d.show();}
}
