'use strict';
(()=>{
 let unlockedPin='',timer;const start=()=>{if(!window.FamilyNative)return;};
 function ask(fields,title){return new Promise(resolve=>{const d=document.createElement('dialog');const h=document.createElement('h2');h.textContent=title;d.append(h);const f=document.createElement('form');for(const field of fields){const label=document.createElement('label');label.textContent=field.label;const input=document.createElement('input');input.name=field.name;input.type=field.type||'text';input.required=true;input.autocomplete='off';input.maxLength=field.name==='pin'?8:10;label.append(input);f.append(label);}const ok=document.createElement('button');ok.textContent='Continuar';ok.className='wide spacer';f.append(ok);const cancel=document.createElement('button');cancel.textContent='Cancelar';cancel.type='button';cancel.className='alt wide spacer';cancel.onclick=()=>{d.close();d.remove();resolve(null);};f.append(cancel);f.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(f));d.close();d.remove();resolve(data);};d.addEventListener('cancel',()=>{d.remove();resolve(null);});d.append(f);document.body.append(d);d.showModal();});}
 async function pin(){if(unlockedPin)return unlockedPin;const value=await ask([{name:'pin',label:'PIN do responsável',type:'password'}],'Acesso protegido');if(!value)throw Error('Acesso cancelado.');unlockedPin=value.pin;clearTimeout(timer);timer=setTimeout(()=>unlockedPin='',300000);return unlockedPin;}
 async function request(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(data)});const body=await r.json();if(!r.ok){if(r.status===403)unlockedPin='';throw Object.assign(Error(body.error),{status:r.status});}return body;}
 async function snapshot(){const childId=sessionStorage.getItem('family-child')||'';try{return await request('/api/web/snapshot',{childId});}catch(e){if(e.status!==401)throw e;const data=await ask([{name:'code',label:'Código do aparelho da criança ou convite de outro responsável'},{name:'pin',label:'PIN do responsável',type:'password'}],'Vincular este computador');if(!data)throw Error('Use Atualizar agora para entrar.');const result=await request('/api/web/pair',data);sessionStorage.setItem('family-child',result.childId);unlockedPin=data.pin;timer=setTimeout(()=>unlockedPin='',300000);return request('/api/web/snapshot',{childId:result.childId});}}
 window.FamilyNative={call:async(id,action,raw)=>{try{const data=JSON.parse(raw);let result;if(action==='snapshot'||action==='sync')result=await snapshot();else if(action==='update'){location.reload();return;}else if(action==='/api/child/claim')throw Error('A criança conclui a tarefa pelo seu aparelho.');else{if(action==='select')action='/api/parent/sync';data.childId??=sessionStorage.getItem('family-child')||'';if(action==='/api/pair'&&!JSON.parse(raw).childId)delete data.childId;data.pin=await pin();result=await request(action,data);if(result.childId)sessionStorage.setItem('family-child',result.childId);}window.nativeReply({id,ok:true,data:result});}catch(e){window.nativeReply({id,ok:false,error:e.message});}}};
 window.addEventListener('blur',()=>unlockedPin='');start();
})();
